In [8]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset = pd.read_excel(r"C:\Users\ANCHAL\Desktop\CODING\M.L\ML PROJECT\lung cancer detection\LUNG CANCER DATASET.xlsx")
dataset

GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
0         M   65        1               1        1              2   
1         F   55        1               2        2              1   
2         F   78        2               2        1              1   
3         M   60        2               1        1              1   
4         F   80        1               1        2              1   
...     ...  ...      ...             ...      ...            ...   
2995      F   71        2               1        1              2   
2996      F   75        1               2        1              1   
2997      F   62        2               2        2              1   
2998      M   30        1               1        2              2   
2999      M   40        1               2        2              1   

      CHRONIC_DISEASE  FATIGUE  ALLERGY  WHEEZING  ALCOHOL_CONSUMING  \
0                   2        1        2         2                  2   
1                   1        2        2         2                  1   
2                   1        2        1         2                  1   
3                   2        1        2         1                  1   
4                   1        2        1         2                  1   
...               ...      ...      ...       ...                ...   
2995                2        1        1         1                  1   
2996                1        2        2         2                  2   
2997                2        2        2         2                  1   
2998                2        2        2         2                  2   
2999                1        1        2         2                  2   

      COUGHING  SHORTNESS_OF_BREATH  SWALLOWING_DIFFICULTY  CHEST_PAIN  \
0            2                    2                      2           1   
1            1                    1                      2           2   
2            1                    2                      1           1   
3            2                    1                      2           2   
4            1                    1                      1           2   
...        ...                  ...                    ...         ...   
2995         2                    1                      1           2   
2996         1                    1                      2           1   
2997         1                    2                      2           2   
2998         1                    2                      1           2   
2999         1                    1                      1           1   

     LUNG_CANCER  
0             NO  
1             NO  
2            YES  
3            YES  
4             NO  
...          ...  
2995          NO  
2996          NO  
2997         YES  
2998         YES  
2999         YES  

[3000 rows x 16 columns]

In [9]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

# Fit and transform the 'Gender' column
dataset['GENDER'] = dataset['GENDER'].replace({'M': 1, 'F': 0})
dataset['LUNG_CANCER'] = dataset['LUNG_CANCER'].replace({'NO': 0, 'YES': 1})
print(dataset)

      GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
0          1   65        1               1        1              2   
1          0   55        1               2        2              1   
2          0   78        2               2        1              1   
3          1   60        2               1        1              1   
4          0   80        1               1        2              1   
...      ...  ...      ...             ...      ...            ...   
2995       0   71        2               1        1              2   
2996       0   75        1               2        1              1   
2997       0   62        2               2        2              1   
2998       1   30        1               1        2              2   
2999       1   40        1               2        2              1   

      CHRONIC_DISEASE  FATIGUE  ALLERGY  WHEEZING  ALCOHOL_CONSUMING  \
0                   2        1        2         2                  2   
1              

In [10]:
#dataset = dataset[~dataset['LUNG_CANCER_encoded'].isin(['0', '1'])]
#dataset = dataset[~dataset['GENDER_encoded'].isin(['0', '1'])]

# unique_genders = dataset['GENDER'].unique()
# print(unique_genders)
# dataset['GENDER'] = dataset['GENDER'].replace('Unknown', pd.NA)
# print(dataset)
# valid_genders = ['F', 'M']

# def clean_gender(GENDER):
#     if GENDER not in valid_genders:
#         return pd.NA  # Replace invalid entry with NaN
#     return GENDER

# dataset['GENDER'] = dataset['GENDER'].apply(clean_gender)
# print(dataset)
# dataset_cleaned = dataset.dropna(subset=['GENDER'])
# print(dataset_cleaned)

In [11]:
# try:
#     dataset['GENDER'] = dataset['GENDER'].astype(float)
#     dataset['AGE'] = dataset['AGE'].astype(float)
#     dataset['LUNG_CANCER'] = dataset['LUNG_CANCER'].astype(float)
# except ValueError as e:
#     print(f"ValueError: {e}")
#     # Handle the error or clean the data
#     # For example, replace 'M' with NaN (Not a Number)
#     dataset['GENDER'] = pd.to_numeric(dataset['GENDER'], errors='coerce')
#     dataset['AGE'] = pd.to_numeric(dataset['AGE'], errors='coerce')
#     dataset['LUNG_CANCER'] = pd.to_numeric(dataset['LUNG_CANCER'], errors='coerce')
# print(dataset)

In [12]:
print(dataset.dtypes)

GENDER                   int64
AGE                      int64
SMOKING                  int64
YELLOW_FINGERS           int64
ANXIETY                  int64
PEER_PRESSURE            int64
CHRONIC_DISEASE          int64
FATIGUE                  int64
ALLERGY                  int64
WHEEZING                 int64
ALCOHOL_CONSUMING        int64
COUGHING                 int64
SHORTNESS_OF_BREATH      int64
SWALLOWING_DIFFICULTY    int64
CHEST_PAIN               int64
LUNG_CANCER              int64
dtype: object


In [69]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.85, random_state = 1)
print (X_train, y_train)

[[ 0 56  1 ...  1  1  1]
 [ 1 54  2 ...  1  1  2]
 [ 1 72  2 ...  1  1  2]
 ...
 [ 0 74  1 ...  1  1  1]
 [ 1 51  1 ...  2  2  2]
 [ 1 60  2 ...  2  1  2]] [1 1 1 0 0 0 0 1 1 0 1 1 0 1 1 1 1 0 0 1 0 0 1 1 1 0 0 0 1 1 0 0 0 0 0 1 1
 1 1 0 1 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 0 1 1 1 0 0 0 0 0 1 1 0 1 0 0 0 0 1
 0 0 0 0 0 1 1 1 0 1 1 1 1 0 0 1 1 1 0 0 1 0 1 0 0 0 1 0 0 1 0 0 1 1 0 0 1
 0 0 1 0 1 1 0 0 1 0 0 0 1 0 0 1 0 1 0 1 0 1 0 1 0 1 0 0 1 0 0 1 1 1 0 0 1
 0 1 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 0 0 1 0 0 0 0 0 1 1 0 1 1 1 1 1 0 0 1
 1 1 0 1 0 1 1 1 1 1 0 1 0 0 0 1 0 0 1 1 0 0 0 0 1 0 1 1 1 1 0 0 0 1 0 0 0
 1 1 1 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 1 1 0 0 1 1 0 1
 0 0 1 1 0 0 1 0 1 1 0 1 1 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 1 0 1 1 0 1 0 1 0
 0 1 1 0 1 1 1 0 1 0 0 0 0 0 1 0 1 0 1 1 1 1 0 0 1 0 1 1 0 0 0 0 0 0 0 1 0
 0 0 1 0 1 1 1 0 1 0 0 1 0 0 1 1 1 0 1 0 1 1 0 1 1 0 0 1 0 0 0 1 1 0 1 0 0
 1 0 1 0 1 1 0 1 0 1 0 1 0 1 1 0 1 1 1 1 0 0 0 1 1 0 0 1 0 0 0 1 0 0 1 0 1
 0 0 0 0 1 0 1 1 1 

In [70]:
from sklearn.linear_model import LinearRegression 
regressor = LinearRegression()
print (X_test, y_test)

[[ 1 30  1 ...  2  1  1]
 [ 0 50  2 ...  2  2  2]
 [ 1 77  2 ...  1  2  1]
 ...
 [ 0 54  1 ...  2  2  1]
 [ 1 32  2 ...  2  2  2]
 [ 0 59  1 ...  1  2  2]] [0 0 1 ... 1 1 1]


In [71]:
regressor.fit(X_train, y_train)

LinearRegression()

In [72]:
regressor.predict(X_train)

array([0.46251278, 0.48068637, 0.51508412, 0.38616743, 0.55358626,
       0.44953729, 0.49845137, 0.59769101, 0.37816346, 0.53544507,
       0.43855037, 0.50628479, 0.53062229, 0.48245331, 0.43232473,
       0.58443603, 0.37323137, 0.38980283, 0.53949842, 0.53284448,
       0.46867166, 0.46515685, 0.402111  , 0.3933511 , 0.45580185,
       0.57531645, 0.3122061 , 0.54690949, 0.53420507, 0.37369317,
       0.57723541, 0.29405995, 0.45191042, 0.50914813, 0.32755715,
       0.39429887, 0.48156536, 0.52170715, 0.39684438, 0.47091225,
       0.46642279, 0.5375362 , 0.32488172, 0.55659065, 0.45941002,
       0.56215518, 0.4385907 , 0.47788908, 0.55519313, 0.50858583,
       0.53042399, 0.46648345, 0.56442477, 0.53730361, 0.50268973,
       0.35802161, 0.42981667, 0.43462352, 0.45589565, 0.4854589 ,
       0.37441647, 0.36324657, 0.45992349, 0.40920096, 0.45937961,
       0.54022606, 0.46087463, 0.47350831, 0.52679657, 0.47987735,
       0.42493591, 0.52361553, 0.40264254, 0.45274025, 0.47197

In [73]:
regressor.score(X_train,y_train)

0.022675678141889866

In [74]:
regressor.score(X_test,y_test)

-0.03342492045561474